ingesup_monte_charge_homepage:
    path:     /
    defaults: { _controller: IngesupMonteChargeBundle:Default:index }

sonata_admin_dashboard_new_user:
    path: /admin/dashboard
    defaults: { _controller: IngesupMonteChargeBundle:User:newUserDashboard }
    methods: [POST]
